# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_script:
  - Rscript -e 'remotes::install_cran(c("devtools", "covr", "pkgdown", "spelling"))'

r:
  - oldrel
  - devel
  - release
os:
  - linux
matrix:
  include:
    - r: release
      os: osx

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'spelling::spell_check_package(vignettes = TRUE)'

deploy:
  - provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
